@REM Backup existing env vars

@if defined R_RPYMAT_CONDA_EXE (
    set "R_RPYMAT_CONDA_EXE_BKUP=%R_RPYMAT_CONDA_EXE%"
)
@set "R_RPYMAT_CONDA_EXE=%CONDA_EXE%"


@if defined R_RPYMAT_CONDA_PREFIX (
    set "R_RPYMAT_CONDA_PREFIX_BKUP=%R_RPYMAT_CONDA_PREFIX%"
)
@set "R_RPYMAT_CONDA_PREFIX=%CONDA_PREFIX%"


@if defined R_RPYMAT_CONDA_PYTHON_EXE (
    set "R_RPYMAT_CONDA_PYTHON_EXE_BKUP=%R_RPYMAT_CONDA_PYTHON_EXE%"
)
@set "R_RPYMAT_CONDA_PYTHON_EXE=%CONDA_PYTHON_EXE%"
