@REM Restore previous env vars

@set "R_RPYMAT_CONDA_EXE="
@if defined R_RPYMAT_CONDA_EXE_BKUP (
  set "R_RPYMAT_CONDA_EXE=%R_RPYMAT_CONDA_EXE_BKUP%"
  set "R_RPYMAT_CONDA_EXE_BKUP="
)

@set "R_RPYMAT_CONDA_PREFIX="
@if defined R_RPYMAT_CONDA_PREFIX_BKUP (
  set "R_RPYMAT_CONDA_PREFIX=%R_RPYMAT_CONDA_PREFIX_BKUP%"
  set "R_RPYMAT_CONDA_PREFIX_BKUP="
)

@set "R_RPYMAT_CONDA_PYTHON_EXE="
@if defined R_RPYMAT_CONDA_PYTHON_EXE_BKUP (
  set "R_RPYMAT_CONDA_PYTHON_EXE=%R_RPYMAT_CONDA_PYTHON_EXE_BKUP%"
  set "R_RPYMAT_CONDA_PYTHON_EXE_BKUP="
)
