# Backup
export R_RPYMAT_CONDA_EXE_BKUP=${R_RPYMAT_CONDA_EXE:-}
export R_RPYMAT_CONDA_PREFIX_BKUP=${R_RPYMAT_CONDA_PREFIX:-}
export R_RPYMAT_CONDA_PYTHON_EXE_BKUP=${R_RPYMAT_CONDA_PYTHON_EXE:-}

# set
export R_RPYMAT_CONDA_EXE="${CONDA_EXE}"
export R_RPYMAT_CONDA_PREFIX="${CONDA_PREFIX}"
export R_RPYMAT_CONDA_PYTHON_EXE="${CONDA_PYTHON_EXE}"

