# Restore previous env vars
export R_RPYMAT_CONDA_EXE=$R_RPYMAT_CONDA_EXE_BKUP
export R_RPYMAT_CONDA_PREFIX=$R_RPYMAT_CONDA_PREFIX_BKUP
export R_RPYMAT_CONDA_PYTHON_EXE=$R_RPYMAT_CONDA_PYTHON_EXE_BKUP

# unset backups
unset R_RPYMAT_CONDA_EXE_BKUP
unset R_RPYMAT_CONDA_PREFIX_BKUP
unset R_RPYMAT_CONDA_PYTHON_EXE_BKUP

if [ -z $R_RPYMAT_CONDA_EXE ]; then
  unset R_RPYMAT_CONDA_EXE
  unset R_RPYMAT_CONDA_PREFIX
  unset R_RPYMAT_CONDA_PYTHON_EXE
fi
